# 0. Based on ubuntu:22.04
FROM ubuntu:22.04

# 1. Create command_tutorial directory in the root directory
# Create firstvi.txt in it
RUN mkdir /command_tutorial
RUN touch /command_tutorial/firstvi.txt

# 2. Install vi
RUN apt update
RUN apt -y install vim